version: '3.8'
services:
  postgres:
    image: postgres:14
    container_name: postgres-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: esereserva123
      POSTGRES_DB: esereservasdb
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5433:5432"

  postgres2:
    image: postgres:14
    container_name: postgres-db2
    environment:
      POSTGRES_USER: admin_reserva
      POSTGRES_PASSWORD: esereserva123
      POSTGRES_DB: reservadb
    volumes:
      - pgdata2:/var/lib/postgresql/data
      - ./init-second.sql:/docker-entrypoint-initdb.d/init-second.sql
    ports:
      - "5434:5432"

  reservas:
    build:
      context: ./Reservas
      dockerfile: Dockerfile
    container_name: reservas_service
    ports:
      - "8080:8080"  # ajuste a porta conforme necessário

  eventos:
    build:
      context: ./Eventos
      dockerfile: Dockerfile
    container_name: eventos_service
    ports:
      - "8081:8080"  # ajuste a porta conforme necessário

  api_gateway:
    build:
      context: ./ApiGatewayESE
      dockerfile: Dockerfile
    container_name: api_gateway_service
    ports:
      - "8082:8080"  # ajuste a porta conforme necessário

volumes:
  pgdata:
  pgdata2: